#! /usr/bin/python
'''
 *  $Id: JobOpt_CalRel_fromRoot, 2015-04-01 18:40:35 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific root data(after Hex2Root)
'''

#-------------------------------------------------------------------
import os
import DMPSW                    # Load DAMPE software
import libDmpCalRel as DmpCalRel

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.SetEventNumber(2000)     # default: -1
#DMPSW.Core.SetStartTime("2014-11-18 20:33:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.SetStopTime("2014-11-18 21:44:10")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141118_163049-Rec0.root")
#DMPSW.RootIOSvc.InputPath(os.environ["DMPSWWORK"]+"/data/sci")
DMPSW.RootIOSvc.SetInputFile("./RelEle.root")
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141030_012521-Rec0.root")
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141118_202446-Rec0.root")  # muon many
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141118_181842-Rec0.root")  # muon P43_68
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141030_125252-Rec0.root")  # muon P93_93
#DMPSW.RootIOSvc.WriteList("Calibration/Bgo")  # split by ;
#DMPSW.RootIOSvc.OutputPath(os.environ["DMPSWWORK"]+"/run/data/cal/mip")

#-------------------------------------------------------------------
# Creat user's service or algorithm
calRel = DmpCalRel.DmpAlgCalibrationRel()
DMPSW.AlgMgr.Append(calRel)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

